"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from .base import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-606156hduf-48egaivubh%*o7*r^g=jz&3kg21x8apg4@i&ee#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# 发送邮箱配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = '1055132129@qq.com'
EMAIL_HOST_PASSWORD = 'hhqwshwbnbhqbfbj'  # 授权码
EMAIL_SUBJECT_PREFIX = '[咸鱼的博客]'
EMAIL_USE_TLS = True  # 与SMTP服务器通信是，是否启动TLS链接（安全链接）
